build:
  image: node:$$NODE_VERSION
  commands:
    - npm install --silent
    - npm test

matrix:
  NODE_VERSION:
    - 4
    - 0.12
    - 0.10

notify:
  email:
    recipients:
      - m+pdfjs@rkusa.st
